name: Build Repository
on: [push]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet Packages
      run: nuget restore Andraste.Host.csproj
 
    - name: Build project
      run: msbuild Andraste.Host.csproj /p:Configuration=Release
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: HostDLL
        path: |
          bin\Release\netstandard2.0\Andraste.Host.dll
          bin\Release\netstandard2.0\Andraste.Host.pdb
